INSERT INTO GROUPS (ID, NAME, C_VAL) VALUES (1, 'Group A', 0);
INSERT INTO GROUPS (ID, NAME, C_VAL) VALUES (2, 'Group B', 0);
INSERT INTO GROUPS (ID, NAME, C_VAL) VALUES (3, 'Group C', 0);

INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (1, 'Ivan Ivanov', 1);
INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (2, 'Maria Petrova', 1);
INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (3, 'Alexey Sidorov', 2);
INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (4, 'Olga Smirnova', 2);
INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (5, 'Dmitry Kozlov', 3);
INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (6, 'Anna Volkova', 3);

SELECT * FROM GROUPS;
SELECT * FROM STUDENTS;
SELECT * FROM STUDENTS_LOG;

DELETE FROM GROUPS WHERE ID = 1;
DELETE FROM GROUPS;
DELETE FROM STUDENTS;
DELETE FROM STUDENTS_LOG;

BEGIN
    restore_students(p_offset => INTERVAL '1' MINUTE);
END;
/